### ISSUE TITLE
models

### ISSUE THREAD

**Issue by CathyLou** [Lowery98/SegNet-on-Automatic-Portrait-Segmentation#1]
请问models这个模块是自己写的吗，没有放出来？
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    from model import *
  File "/nvme/louming/projects/SegNet-on-Automatic-Portrait-Segmentation/model.py", line 1, in <module>
    from models.segnet import *
ModuleNotFoundError: No module named 'models'

**Comment by wangmengmeng99** [comment]
这是个models文件夹，你可以选择新建一个models文件把所有的segnet.py，vgg.py等文件放进去，也可以选择修改代码，把代码里的models.去掉

**Comment by CathyLou** [comment]
谢谢你呀，去年刚入python坑时问的zz问题竟然有人耐心解答了，真是个nice的小姐姐，大赞👍
